### ISSUE TITLE
Create more uscase scripts

### ISSUE THREAD

**Issue by tvladyslav** [novemus/plexus#1]
Would be nice to have more predefined scripts for popular P2P actions like:

1. wireguard
2. scp
3. rsync
4. ssh

**Comment by novemus** [comment]
> Would be nice to have more predefined scripts for popular P2P actions

That's a great idea. I really hope that the community will join in its implementation. But I don't have a lot of time, so I try to spend it on core development, but I will replenish the collection as much as possible. It may be worth opening a separate submodule for this.
